###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "test4",
    "author": "author",
    "url": "http://url.com",
    "likes": 5
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "test",
    "name": "Test man",
    "password": "password"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "arto",
    "name": "Arto Hellas",
    "password": "password"
}
###
GET http://localhost:3003/api/users
